export interface User {
    id: number,
    email: string,
    username: string,
    password: string,
    firstName: string,
    lastName: string,
    gender: string,
    phone: number,
    birthDate: string,
    role: string,
    adress: string,
    number: number,
    city: string,
    state: string,
    country: string,
    zip_code: number,
}